/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ImageId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TagId = IDL.Text;
export const Tag = IDL.Record({
  'id' : TagId,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ContactConfig = IDL.Record({
  'wechatBlob' : IDL.Opt(ExternalBlob),
  'qqBlob' : IDL.Opt(ExternalBlob),
  'xiaohongshuBlob' : IDL.Opt(ExternalBlob),
});
export const AIImage = IDL.Record({
  'id' : ImageId,
  'blob' : ExternalBlob,
  'size' : IDL.Nat,
  'fileName' : IDL.Text,
  'tagIds' : IDL.Vec(IDL.Text),
  'uploadedAt' : IDL.Int,
});
export const PaymentConfig = IDL.Record({
  'alipayBlob' : IDL.Opt(ExternalBlob),
  'wechatBlob' : IDL.Opt(ExternalBlob),
  'priceText' : IDL.Text,
});
export const WatermarkConfig = IDL.Record({
  'blob' : IDL.Opt(ExternalBlob),
  'scale' : IDL.Float64,
  'enabled' : IDL.Bool,
  'positionX' : IDL.Float64,
  'positionY' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addImage' : IDL.Func(
      [ExternalBlob, IDL.Vec(IDL.Text), IDL.Text, IDL.Nat],
      [ImageId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTag' : IDL.Func([IDL.Text], [TagId], []),
  'deleteImage' : IDL.Func([ImageId], [], []),
  'deleteTag' : IDL.Func([TagId], [], []),
  'getAllTags' : IDL.Func([], [IDL.Vec(Tag)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactConfig' : IDL.Func([], [ContactConfig], ['query']),
  'getImage' : IDL.Func([ImageId], [AIImage], ['query']),
  'getImageCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getImagesByTag' : IDL.Func([TagId], [IDL.Vec(AIImage)], ['query']),
  'getImagesByTags' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Vec(AIImage)],
      ['query'],
    ),
  'getLatestImages' : IDL.Func([IDL.Nat], [IDL.Vec(AIImage)], ['query']),
  'getPaymentConfig' : IDL.Func([], [PaymentConfig], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWatermarkConfig' : IDL.Func([], [WatermarkConfig], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateContactConfig' : IDL.Func([ContactConfig], [], []),
  'updatePaymentConfig' : IDL.Func([PaymentConfig], [], []),
  'updateWatermarkConfig' : IDL.Func([WatermarkConfig], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ImageId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TagId = IDL.Text;
  const Tag = IDL.Record({
    'id' : TagId,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ContactConfig = IDL.Record({
    'wechatBlob' : IDL.Opt(ExternalBlob),
    'qqBlob' : IDL.Opt(ExternalBlob),
    'xiaohongshuBlob' : IDL.Opt(ExternalBlob),
  });
  const AIImage = IDL.Record({
    'id' : ImageId,
    'blob' : ExternalBlob,
    'size' : IDL.Nat,
    'fileName' : IDL.Text,
    'tagIds' : IDL.Vec(IDL.Text),
    'uploadedAt' : IDL.Int,
  });
  const PaymentConfig = IDL.Record({
    'alipayBlob' : IDL.Opt(ExternalBlob),
    'wechatBlob' : IDL.Opt(ExternalBlob),
    'priceText' : IDL.Text,
  });
  const WatermarkConfig = IDL.Record({
    'blob' : IDL.Opt(ExternalBlob),
    'scale' : IDL.Float64,
    'enabled' : IDL.Bool,
    'positionX' : IDL.Float64,
    'positionY' : IDL.Float64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addImage' : IDL.Func(
        [ExternalBlob, IDL.Vec(IDL.Text), IDL.Text, IDL.Nat],
        [ImageId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTag' : IDL.Func([IDL.Text], [TagId], []),
    'deleteImage' : IDL.Func([ImageId], [], []),
    'deleteTag' : IDL.Func([TagId], [], []),
    'getAllTags' : IDL.Func([], [IDL.Vec(Tag)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactConfig' : IDL.Func([], [ContactConfig], ['query']),
    'getImage' : IDL.Func([ImageId], [AIImage], ['query']),
    'getImageCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getImagesByTag' : IDL.Func([TagId], [IDL.Vec(AIImage)], ['query']),
    'getImagesByTags' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Vec(AIImage)],
        ['query'],
      ),
    'getLatestImages' : IDL.Func([IDL.Nat], [IDL.Vec(AIImage)], ['query']),
    'getPaymentConfig' : IDL.Func([], [PaymentConfig], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWatermarkConfig' : IDL.Func([], [WatermarkConfig], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateContactConfig' : IDL.Func([ContactConfig], [], []),
    'updatePaymentConfig' : IDL.Func([PaymentConfig], [], []),
    'updateWatermarkConfig' : IDL.Func([WatermarkConfig], [], []),
  });
};

export const init = ({ IDL }) => { return []; };