/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIImage {
  'id' : ImageId,
  'blob' : ExternalBlob,
  'size' : bigint,
  'fileName' : string,
  'tagIds' : Array<string>,
  'uploadedAt' : bigint,
}
export interface ContactConfig {
  'wechatBlob' : [] | [ExternalBlob],
  'qqBlob' : [] | [ExternalBlob],
  'xiaohongshuBlob' : [] | [ExternalBlob],
}
export type ExternalBlob = Uint8Array;
export type ImageId = string;
export interface PaymentConfig {
  'alipayBlob' : [] | [ExternalBlob],
  'wechatBlob' : [] | [ExternalBlob],
  'priceText' : string,
}
export interface Tag { 'id' : TagId, 'name' : string, 'createdAt' : bigint }
export type TagId = string;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WatermarkConfig {
  'blob' : [] | [ExternalBlob],
  'scale' : number,
  'enabled' : boolean,
  'positionX' : number,
  'positionY' : number,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addImage' : ActorMethod<
    [ExternalBlob, Array<string>, string, bigint],
    ImageId
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTag' : ActorMethod<[string], TagId>,
  'deleteImage' : ActorMethod<[ImageId], undefined>,
  'deleteTag' : ActorMethod<[TagId], undefined>,
  'getAllTags' : ActorMethod<[], Array<Tag>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactConfig' : ActorMethod<[], ContactConfig>,
  'getImage' : ActorMethod<[ImageId], AIImage>,
  'getImageCount' : ActorMethod<[], bigint>,
  'getImagesByTag' : ActorMethod<[TagId], Array<AIImage>>,
  'getImagesByTags' : ActorMethod<[Array<string>], Array<AIImage>>,
  'getLatestImages' : ActorMethod<[bigint], Array<AIImage>>,
  'getPaymentConfig' : ActorMethod<[], PaymentConfig>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWatermarkConfig' : ActorMethod<[], WatermarkConfig>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateContactConfig' : ActorMethod<[ContactConfig], undefined>,
  'updatePaymentConfig' : ActorMethod<[PaymentConfig], undefined>,
  'updateWatermarkConfig' : ActorMethod<[WatermarkConfig], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];